### ISSUE TITLE
anti-tracking: TypeError: this.processEntry.pub

### ISSUE THREAD

**Issue by philipp-classen** [whotracksme/webextension-packages#135]
Seen on 10.4.14, on Chrome:

```
cached-entry-pipeline.js:168 Uncaught (in promise) TypeError: this.processEntry.pub is not a function
    at cached-entry-pipeline.js:168:55
    at Array.forEach (<anonymous>)
    at KeyPipeline.clean (cached-entry-pipeline.js:168:22)
    at async index.js:112:7
```

```
    // push first maxSending entries to input queue
    queuedForSending.splice(maxSending);
    queuedForSending.forEach((v) => this.processEntry.pub(v));  <--- HERE
    // delete old entries
    this.db.bulkDelete(toBeDeleted);
```

Most likely fixed by https://github.com/whotracksme/webextension-packages/pull/134

**Comment by philipp-classen** [comment]
Graphs confirm that it is fixed.
